[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 2000
enableCORS = false
enableXsrfProtection = true
maxMessageSize = 2000

[browser]
gatherUsageStats = false
